DO $$
DECLARE
  v_0 UUID;
  v_1 UUID;
  v_2 UUID;
  v_3 UUID;
BEGIN
  INSERT INTO vendors (name) SELECT 'TrackMaster Corp' WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE name = 'TrackMaster Corp');
  SELECT vendor_id INTO v_0 FROM vendors WHERE name = 'TrackMaster Corp' LIMIT 1;
  INSERT INTO vendors (name) SELECT 'PadTech Industries' WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE name = 'PadTech Industries');
  SELECT vendor_id INTO v_1 FROM vendors WHERE name = 'PadTech Industries' LIMIT 1;
  INSERT INTO vendors (name) SELECT 'ClipCorp Solutions' WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE name = 'ClipCorp Solutions');
  SELECT vendor_id INTO v_2 FROM vendors WHERE name = 'ClipCorp Solutions' LIMIT 1;
  INSERT INTO vendors (name) SELECT 'RailTech Industries' WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE name = 'RailTech Industries');
  SELECT vendor_id INTO v_3 FROM vendors WHERE name = 'RailTech Industries' LIMIT 1;
  INSERT INTO assets (type, location, vendor_id, install_date, warranty_period, health_score, status, condition, metadata) VALUES 
  ('Elastic Rail Clip', 'Platform 1 Section A', v_3, '2023-01-15', 36, 85, 'active', 'good', '{"description": "High-strength elastic rail clip for platform section", "serial_number": "ERC-001", "model": "Model-X", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Junction Point B-12', v_0, '2023-02-20', 24, 92, 'active', 'excellent', '{"description": "Vibration dampening rail pad with enhanced durability", "serial_number": "RP-001", "model": "Heavy-Duty", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Bridge Crossing C-45', v_2, '2022-12-10', 60, 78, 'under_maintenance', 'good', '{"description": "Track liner component requiring scheduled maintenance", "serial_number": "LNR-001", "model": "Pro-Line", "manufacturer": "LinerCorp", "health_category": "Good"}'::jsonb),
  ('Sleeper', 'Platform 2 Section D', v_1, '2023-03-05', 30, 88, 'active', 'good', '{"description": "Concrete railway sleeper with reinforcement", "serial_number": "SLP-001", "model": "Heavy-Duty", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Junction Point E-67', v_3, '2023-01-22', 36, 73, 'active', 'ok', '{"description": "Standard elastic rail clip with moderate wear", "serial_number": "ERC-002", "model": "Model-X", "manufacturer": "ClipCorp", "health_category": "Ok"}'::jsonb),
  ('Rail Pad', 'Maintenance Yard F', v_0, '2023-04-18', 24, 95, 'active', 'excellent', '{"description": "Premium vibration dampening pad for high-traffic area", "serial_number": "RP-002", "model": "Ultra-Heavy", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Bridge Section G-89', v_2, '2022-11-30', 60, 45, 'under_maintenance', 'critical', '{"description": "Track liner showing signs of wear requiring immediate attention", "serial_number": "LNR-002", "model": "Pro-Line", "manufacturer": "LinerCorp", "health_category": "Critical"}'::jsonb),
  ('Sleeper', 'Platform 3 Section H', v_1, '2023-02-15', 30, 82, 'active', 'good', '{"description": "Precast concrete sleeper with standard specifications", "serial_number": "SLP-002", "model": "Standard", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Signal Box Area I', v_3, '2023-03-12', 36, 67, 'active', 'ok', '{"description": "Rail clip in signal control area with regular inspection", "serial_number": "ERC-003", "model": "Model-Y", "manufacturer": "ClipCorp", "health_category": "Ok"}'::jsonb),
  ('Rail Pad', 'Depot Junction J-34', v_0, '2023-05-08', 24, 89, 'active', 'good', '{"description": "High-performance rail pad for depot operations", "serial_number": "RP-003", "model": "Depot-Grade", "manufacturer": "PadTech", "health_category": "Good"}'::jsonb),
  ('Liner', 'Tunnel Section K-12', v_2, '2022-10-25', 60, 91, 'active', 'excellent', '{"description": "Tunnel-grade liner with enhanced corrosion resistance", "serial_number": "LNR-003", "model": "Tunnel-Pro", "manufacturer": "LinerCorp", "health_category": "Excellent"}'::jsonb),
  ('Sleeper', 'Freight Yard L-56', v_1, '2023-01-30', 30, 76, 'active', 'good', '{"description": "Heavy-duty sleeper for freight operations", "serial_number": "SLP-003", "model": "Freight-Heavy", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Station Platform M', v_3, '2023-04-05', 36, 84, 'active', 'good', '{"description": "Platform rail clip with passenger safety certification", "serial_number": "ERC-004", "model": "Station-Grade", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Express Line N-78', v_0, '2023-06-12', 24, 93, 'active', 'excellent', '{"description": "High-speed rail pad for express train operations", "serial_number": "RP-004", "model": "Express-Pro", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Curve Section O-23', v_2, '2022-09-18', 60, 62, 'active', 'ok', '{"description": "Curved track liner with specialized geometry", "serial_number": "LNR-004", "model": "Curve-Spec", "manufacturer": "LinerCorp", "health_category": "Ok"}'::jsonb),
  ('Sleeper', 'Industrial Siding P', v_1, '2023-02-28', 30, 71, 'active', 'ok', '{"description": "Industrial-grade sleeper for heavy cargo loads", "serial_number": "SLP-004", "model": "Industrial", "manufacturer": "SleeperTech", "health_category": "Ok"}'::jsonb),
  ('Elastic Rail Clip', 'Maintenance Shop Q', v_3, '2023-05-15', 36, 39, 'under_maintenance', 'critical', '{"description": "Shop area rail clip requiring urgent replacement", "serial_number": "ERC-005", "model": "Workshop", "manufacturer": "ClipCorp", "health_category": "Critical"}'::jsonb),
  ('Rail Pad', 'Loading Dock R-45', v_0, '2023-07-22', 24, 87, 'active', 'good', '{"description": "Specialized pad for loading dock operations", "serial_number": "RP-005", "model": "Dock-Spec", "manufacturer": "PadTech", "health_category": "Good"}'::jsonb),
  ('Liner', 'Switching Yard S-67', v_2, '2022-08-14', 60, 94, 'active', 'excellent', '{"description": "Switching yard liner with enhanced durability", "serial_number": "LNR-005", "model": "Switch-Pro", "manufacturer": "LinerCorp", "health_category": "Excellent"}'::jsonb),
  ('Sleeper', 'Passenger Terminal T', v_1, '2023-03-18', 30, 79, 'active', 'good', '{"description": "Terminal sleeper with aesthetic considerations", "serial_number": "SLP-005", "model": "Terminal-Grade", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Fuel Depot U-12', v_3, '2023-06-08', 36, 81, 'active', 'good', '{"description": "Fuel depot rail clip with safety specifications", "serial_number": "ERC-006", "model": "Safety-Pro", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Inspection Point V', v_0, '2023-08-15', 24, 96, 'active', 'excellent', '{"description": "Inspection area pad with monitoring capabilities", "serial_number": "RP-006", "model": "Monitor-Pro", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Emergency Siding W-34', v_2, '2022-07-20', 60, 55, 'active', 'ok', '{"description": "Emergency siding liner for safety operations", "serial_number": "LNR-006", "model": "Emergency", "manufacturer": "LinerCorp", "health_category": "Ok"}'::jsonb),
  ('Sleeper', 'Control Tower X-89', v_1, '2023-04-12', 30, 83, 'active', 'good', '{"description": "Control area sleeper with communication cable routing", "serial_number": "SLP-006", "model": "Control-Spec", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Wash Bay Y-56', v_3, '2023-07-25', 36, 68, 'active', 'ok', '{"description": "Wash bay rail clip with corrosion resistance", "serial_number": "ERC-007", "model": "Wash-Resistant", "manufacturer": "ClipCorp", "health_category": "Ok"}'::jsonb),
  ('Rail Pad', 'Test Track Z-78', v_0, '2023-09-18', 24, 91, 'active', 'excellent', '{"description": "Test track pad for equipment validation", "serial_number": "RP-007", "model": "Test-Grade", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Overpass Section AA', v_2, '2022-06-15', 60, 86, 'active', 'good', '{"description": "Overpass liner with structural support features", "serial_number": "LNR-007", "model": "Bridge-Pro", "manufacturer": "LinerCorp", "health_category": "Good"}'::jsonb),
  ('Sleeper', 'Underpass Section BB', v_1, '2023-05-22', 30, 74, 'active', 'ok', '{"description": "Underpass sleeper with drainage considerations", "serial_number": "SLP-007", "model": "Drainage-Pro", "manufacturer": "SleeperTech", "health_category": "Ok"}'::jsonb),
  ('Elastic Rail Clip', 'Parking Yard CC-23', v_3, '2023-08-30', 36, 77, 'active', 'good', '{"description": "Parking yard clip for rolling stock storage", "serial_number": "ERC-008", "model": "Storage-Grade", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Workshop DD-45', v_0, '2023-10-12', 24, 88, 'active', 'good', '{"description": "Workshop rail pad for maintenance operations", "serial_number": "RP-008", "model": "Workshop-Pro", "manufacturer": "PadTech", "health_category": "Good"}'::jsonb),
  ('Liner', 'Signal Bridge EE', v_2, '2022-05-28', 60, 92, 'active', 'excellent', '{"description": "Signal bridge liner with cable management", "serial_number": "LNR-008", "model": "Signal-Pro", "manufacturer": "LinerCorp", "health_category": "Excellent"}'::jsonb),
  ('Sleeper', 'Crossover Point FF', v_1, '2023-06-15', 30, 65, 'active', 'ok', '{"description": "Crossover sleeper for track intersection", "serial_number": "SLP-008", "model": "Crossover", "manufacturer": "SleeperTech", "health_category": "Ok"}'::jsonb),
  ('Elastic Rail Clip', 'Service Road GG-67', v_3, '2023-09-08', 36, 85, 'active', 'good', '{"description": "Service road clip for maintenance vehicle access", "serial_number": "ERC-009", "model": "Service-Pro", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Equipment Shed HH', v_0, '2023-11-22', 24, 90, 'active', 'excellent', '{"description": "Equipment storage area rail pad", "serial_number": "RP-009", "model": "Storage-Pro", "manufacturer": "PadTech", "health_category": "Good"}'::jsonb),
  ('Liner', 'Access Bridge II-89', v_2, '2022-04-18', 60, 58, 'active', 'ok', '{"description": "Access bridge liner for personnel crossing", "serial_number": "LNR-009", "model": "Access-Pro", "manufacturer": "LinerCorp", "health_category": "Ok"}'::jsonb),
  ('Sleeper', 'Safety Zone JJ-12', v_1, '2023-07-28', 30, 80, 'active', 'good', '{"description": "Safety zone sleeper with emergency features", "serial_number": "SLP-009", "model": "Safety-Pro", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Crane Area KK-34', v_3, '2023-10-15', 36, 72, 'active', 'ok', '{"description": "Crane area clip for heavy lifting operations", "serial_number": "ERC-010", "model": "Crane-Spec", "manufacturer": "ClipCorp", "health_category": "Ok"}'::jsonb),
  ('Rail Pad', 'Buffer Zone LL-56', v_0, '2023-12-05', 24, 94, 'active', 'excellent', '{"description": "Buffer zone pad for impact absorption", "serial_number": "RP-010", "model": "Buffer-Pro", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Drainage Channel MM', v_2, '2022-03-25', 60, 87, 'active', 'good', '{"description": "Drainage channel liner with water management", "serial_number": "LNR-010", "model": "Drain-Pro", "manufacturer": "LinerCorp", "health_category": "Good"}'::jsonb),
  ('Sleeper', 'Platform Edge NN-78', v_1, '2023-08-18', 30, 69, 'active', 'ok', '{"description": "Platform edge sleeper with safety barriers", "serial_number": "SLP-010", "model": "Edge-Safe", "manufacturer": "SleeperTech", "health_category": "Ok"}'::jsonb),
  ('Elastic Rail Clip', 'Ventilation Shaft OO', v_3, '2023-11-12', 36, 83, 'active', 'good', '{"description": "Ventilation area clip with airflow considerations", "serial_number": "ERC-011", "model": "Vent-Pro", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Emergency Exit PP-23', v_0, '2024-01-08', 24, 89, 'active', 'good', '{"description": "Emergency exit rail pad with safety certification", "serial_number": "RP-011", "model": "Emergency-Pro", "manufacturer": "PadTech", "health_category": "Good"}'::jsonb),
  ('Liner', 'Cable Duct QQ-45', v_2, '2022-02-14', 60, 75, 'active', 'good', '{"description": "Cable duct liner for electrical systems", "serial_number": "LNR-011", "model": "Cable-Pro", "manufacturer": "LinerCorp", "health_category": "Good"}'::jsonb),
  ('Sleeper', 'Monitoring Station RR', v_1, '2023-09-25', 30, 86, 'active', 'good', '{"description": "Monitoring station sleeper with sensor integration", "serial_number": "SLP-011", "model": "Monitor-Pro", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb),
  ('Elastic Rail Clip', 'Fire Station SS-67', v_3, '2023-12-18', 36, 78, 'active', 'good', '{"description": "Fire station area clip with emergency access", "serial_number": "ERC-012", "model": "Fire-Safe", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'First Aid Point TT', v_0, '2024-02-15', 24, 92, 'active', 'excellent', '{"description": "First aid point rail pad with medical equipment access", "serial_number": "RP-012", "model": "Medical-Pro", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Communication Tower UU', v_2, '2022-01-20', 60, 81, 'active', 'good', '{"description": "Communication tower liner with signal equipment", "serial_number": "LNR-012", "model": "Comm-Pro", "manufacturer": "LinerCorp", "health_category": "Good"}'::jsonb),
  ('Sleeper', 'Weather Station VV-89', v_1, '2023-10-30', 30, 73, 'active', 'ok', '{"description": "Weather monitoring sleeper with instrument mounting", "serial_number": "SLP-012", "model": "Weather-Pro", "manufacturer": "SleeperTech", "health_category": "Ok"}'::jsonb),
  ('Elastic Rail Clip', 'Security Gate WW-12', v_3, '2024-01-25', 36, 88, 'active', 'good', '{"description": "Security gate clip with access control integration", "serial_number": "ERC-013", "model": "Security-Pro", "manufacturer": "ClipCorp", "health_category": "Good"}'::jsonb),
  ('Rail Pad', 'Visitor Center XX-34', v_0, '2024-03-12', 24, 95, 'active', 'excellent', '{"description": "Visitor center rail pad with public access considerations", "serial_number": "RP-013", "model": "Public-Pro", "manufacturer": "PadTech", "health_category": "Excellent"}'::jsonb),
  ('Liner', 'Information Board YY', v_2, '2021-12-18', 60, 42, 'retired', 'good', '{"description": "LNR-013", "serial_number": "Info-Pro", "model": "LinerCorp", "manufacturer": null, "health_category": "retired"}'::jsonb),
  ('Sleeper', 'Archive Building ZZ-56', v_1, '2023-11-15', 30, 84, 'active', 'good', '{"description": "Archive building sleeper with document storage access", "serial_number": "SLP-013", "model": "Archive-Pro", "manufacturer": "SleeperTech", "health_category": "Good"}'::jsonb);
END $$;
